# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4a04c2c22fce7219b579d213a7a85a59084fde9ce12587cfc0203403a6ddfee1aaba02290ad5b7054e8d251e95f32893422e93301b8bafca277cb02b2b6342b

test:
  secret_key_base: a16724e156ba8a6927b1865b779725d97d0adf59fb0d9dc09ad7a1aa7edf09181c1f8efba9a4c6f20a80c36fb54a4f029b662753f5e780724c3e569d5b3f2ce9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
